apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.name}}-env-config
  annotations:
    harness.io/skip-versioning: "true"
data:
  {{.Values.env.config | toYaml | indent 2}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}-deployment
  labels:
    app: {{.Values.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
        - name: {{.Values.name}}
          image: {{.Values.image}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-service
  labels:
    app: {{.Values.name}}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{.Values.name}}
---
{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/timeout: 300s
    haproxy.router.openshift.io/rewrite-target: /
  name: {{.Values.name}}-routes
  labels:
    router: internal
    app: {{.Values.name}}
spec:
  host: {{.Values.urlName}}-{{.Values.namespace}}.{{.Values.gatewayHostname}}
  path: /
  to:
    kind: Service
    name: {{.Values.name}}-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}